export const PRODUCT_REQ="PRODUCT_REQ"
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS"
export const PRODUCT_FAIL="PRODUCT_FAIL"
export const SEARCH_REQ = 'SEARCH_REQ'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'
